### ISSUE TITLE
Any instruction on how to use it?

### ISSUE THREAD

**Issue by bbird81** [achelak/AudiocodesCDRChecker#1]
Hi! Your project looks very promising... but I don't know how to install/use it, would you mind writing down a few lines of instructions on how to build it up? That would be awesome :)

Thanks!

**Comment by achelak** [comment]
Hi @bbird81, thank you for your interest in this project. 
Unfortunately, this was a solution for a specific task in a specific company and I doubt that it will satisfy your needs.
But, the idea was pretty simple:

- Set up sending CDRs to a REST API from an AudioCodes SBC.
- Receive CDRs using a custom REST [API](https://github.com/achelak/CDRAPIReceiverAudiocodesSBC).
- Store CDRs in an SQL database.
- View the CDRs using this project.

To get acquainted with the project, you can try to install it using this Ansible [role](https://github.com/achelak/Ansible-role-CDRCheckerDeploymentMinimal), which sets up Docker on your Linux machine (ubuntu) and a group of services using Docker Compose.
I'm not sure if it will work after so many years but you can try;)

**Comment by bbird81** [comment]
Ok thanks, I'll give it shot! Thanks for answering and explaining! :)
